spring:
  datasource:
    url: jdbc:mysql://47.106.142.130:3306/imiros?serverTimezone=UTC
    username: root
    password: 951023
    #    password: Qq330640++
    driver-class-name: com.mysql.cj.jdbc.Driver
    thymeleaf:
      prefix: classpath:/templates

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml

logging:
  level:
    com:
      vip:
        zh:
          dao: debug
