spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/imiros?serverTimezone=UTC
    username: root
      password: 951023
    #    password: Qq330640++
    driver-class-name: com.mysql.cj.jdbc.Driver

    thymeleaf:
      prefix: classpath:/templates

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.vip.zh.pojo

logging:
  level:
    com:
      vip:
        zh:
          dao: debug
server:
  port: 80
